const WIDTH = 480;
const HEIGHT = 640;
const COURT_PADDING = 40;
const FREE_THROW_ZONE_WIDTH = WIDTH - 2 * COURT_PADDING - 40;
const RECT_WIDTH = 90;
const RECT_HEIGHT = 110;
const CENTER_CIRCLE_RADIUS = RECT_WIDTH;

const PLAYER_SPEED = 2;
const PLAYER_FAST_SPEED = 4;
const MAX_STAMINA = 60;
